/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as StoreRouteRouteImport } from './routes/store/route'
import { Route as ProductRouteRouteImport } from './routes/product/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as StoreCheckoutRouteImport } from './routes/store/checkout'
import { Route as StoreProductIdRouteImport } from './routes/store/$productId'
import { Route as OrderOrderIdRouteImport } from './routes/order/$orderId'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardMiscRouteImport } from './routes/dashboard/misc'
import { Route as DashboardCollectionsRouteImport } from './routes/dashboard/collections'
import { Route as DashboardCategoriesRouteImport } from './routes/dashboard/categories'
import { Route as DashboardBrandsRouteImport } from './routes/dashboard/brands'
import { Route as DashboardAttributesRouteImport } from './routes/dashboard/attributes'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRouteRoute = StoreRouteRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRouteRoute = ProductRouteRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreProductIdRoute = StoreProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => StoreRouteRoute,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMiscRoute = DashboardMiscRouteImport.update({
  id: '/misc',
  path: '/misc',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCollectionsRoute = DashboardCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCategoriesRoute = DashboardCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBrandsRoute = DashboardBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAttributesRoute = DashboardAttributesRouteImport.update({
  id: '/attributes',
  path: '/attributes',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/product': typeof ProductRouteRoute
  '/store': typeof StoreRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/dashboard/attributes': typeof DashboardAttributesRoute
  '/dashboard/brands': typeof DashboardBrandsRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/collections': typeof DashboardCollectionsRoute
  '/dashboard/misc': typeof DashboardMiscRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/store/$productId': typeof StoreProductIdRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/store/': typeof StoreIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product': typeof ProductRouteRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/dashboard/attributes': typeof DashboardAttributesRoute
  '/dashboard/brands': typeof DashboardBrandsRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/collections': typeof DashboardCollectionsRoute
  '/dashboard/misc': typeof DashboardMiscRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/store/$productId': typeof StoreProductIdRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/dashboard': typeof DashboardIndexRoute
  '/store': typeof StoreIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/product': typeof ProductRouteRoute
  '/store': typeof StoreRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/dashboard/attributes': typeof DashboardAttributesRoute
  '/dashboard/brands': typeof DashboardBrandsRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/collections': typeof DashboardCollectionsRoute
  '/dashboard/misc': typeof DashboardMiscRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/store/$productId': typeof StoreProductIdRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/store/': typeof StoreIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/product'
    | '/store'
    | '/about'
    | '/contact'
    | '/contacts'
    | '/delivery'
    | '/login'
    | '/redirect'
    | '/dashboard/attributes'
    | '/dashboard/brands'
    | '/dashboard/categories'
    | '/dashboard/collections'
    | '/dashboard/misc'
    | '/dashboard/orders'
    | '/order/$orderId'
    | '/store/$productId'
    | '/store/checkout'
    | '/dashboard/'
    | '/store/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/product'
    | '/about'
    | '/contact'
    | '/contacts'
    | '/delivery'
    | '/login'
    | '/redirect'
    | '/dashboard/attributes'
    | '/dashboard/brands'
    | '/dashboard/categories'
    | '/dashboard/collections'
    | '/dashboard/misc'
    | '/dashboard/orders'
    | '/order/$orderId'
    | '/store/$productId'
    | '/store/checkout'
    | '/dashboard'
    | '/store'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/product'
    | '/store'
    | '/about'
    | '/contact'
    | '/contacts'
    | '/delivery'
    | '/login'
    | '/redirect'
    | '/dashboard/attributes'
    | '/dashboard/brands'
    | '/dashboard/categories'
    | '/dashboard/collections'
    | '/dashboard/misc'
    | '/dashboard/orders'
    | '/order/$orderId'
    | '/store/$productId'
    | '/store/checkout'
    | '/dashboard/'
    | '/store/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ProductRouteRoute: typeof ProductRouteRoute
  StoreRouteRoute: typeof StoreRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ContactsRoute: typeof ContactsRoute
  DeliveryRoute: typeof DeliveryRoute
  LoginRoute: typeof LoginRoute
  RedirectRoute: typeof RedirectRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/store/checkout': {
      id: '/store/checkout'
      path: '/checkout'
      fullPath: '/store/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/$productId': {
      id: '/store/$productId'
      path: '/$productId'
      fullPath: '/store/$productId'
      preLoaderRoute: typeof StoreProductIdRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/misc': {
      id: '/dashboard/misc'
      path: '/misc'
      fullPath: '/dashboard/misc'
      preLoaderRoute: typeof DashboardMiscRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/collections': {
      id: '/dashboard/collections'
      path: '/collections'
      fullPath: '/dashboard/collections'
      preLoaderRoute: typeof DashboardCollectionsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/categories': {
      id: '/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/brands': {
      id: '/dashboard/brands'
      path: '/brands'
      fullPath: '/dashboard/brands'
      preLoaderRoute: typeof DashboardBrandsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/attributes': {
      id: '/dashboard/attributes'
      path: '/attributes'
      fullPath: '/dashboard/attributes'
      preLoaderRoute: typeof DashboardAttributesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAttributesRoute: typeof DashboardAttributesRoute
  DashboardBrandsRoute: typeof DashboardBrandsRoute
  DashboardCategoriesRoute: typeof DashboardCategoriesRoute
  DashboardCollectionsRoute: typeof DashboardCollectionsRoute
  DashboardMiscRoute: typeof DashboardMiscRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAttributesRoute: DashboardAttributesRoute,
  DashboardBrandsRoute: DashboardBrandsRoute,
  DashboardCategoriesRoute: DashboardCategoriesRoute,
  DashboardCollectionsRoute: DashboardCollectionsRoute,
  DashboardMiscRoute: DashboardMiscRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface StoreRouteRouteChildren {
  StoreProductIdRoute: typeof StoreProductIdRoute
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StoreIndexRoute: typeof StoreIndexRoute
}

const StoreRouteRouteChildren: StoreRouteRouteChildren = {
  StoreProductIdRoute: StoreProductIdRoute,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StoreIndexRoute: StoreIndexRoute,
}

const StoreRouteRouteWithChildren = StoreRouteRoute._addFileChildren(
  StoreRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ProductRouteRoute: ProductRouteRoute,
  StoreRouteRoute: StoreRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ContactsRoute: ContactsRoute,
  DeliveryRoute: DeliveryRoute,
  LoginRoute: LoginRoute,
  RedirectRoute: RedirectRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
